### PR TITLE
Add crass module.

### PR DESCRIPTION
**Pull request by ben-eb**
Nice optimiser; can minimise colour declarations such as rgba to hsla.

### CODE REVIEW

**Comment by jakubpawlowicz** [comment]
Could you please also run `npm run bench` to include `crass` results (ideally squashed into 1 commit)? Thanks!

**Comment by ben-eb** [comment]
Rebased, squashed commits. :+1:

**Comment by XhmikosR** [comment]
So many tools... If only people preferred to improve the existent tools instead of doing something new.

I guess that's one of the (dis)advantages of open source :/

**Comment by jakubpawlowicz** [comment]
Yup, classic - http://xkcd.com/927/

**Pull request merged**
