### PR TITLE
updating minification engines no last stable version

### PR DESCRIPTION
**Pull request by diegourban**
#57 

### clean-css

API Call seems to be compatible.

Just adapted the options:

- 'processImport: false' to 'inline: false';
- 'advanced off' to level 1 (default), so 'advanced: on' would be level 2, am I right?

### crass

API Call and options seems to be compatible.

### cssnano

API Call and options seems to be compatible.

### csso

API Call and options seems to be compatible.

### csswring

API Call and options seems to be compatible.

### CODE REVIEW

**Comment by XhmikosR** [comment]
It seems you missed package-lock.json.

**Comment by diegourban** [comment]
My package-lock.json file didn't updated after package.json was changed.

I just tried the following:

`rm -rf node_modules`
`npm install`

This makes no changes: package.json shows clean-css 4.1.x, node_modules/clean-css/package.json shows 4.1.9 and package-lock.json still shows 3.4.28. The same for the other updates...

Any ideas?

**Comment by XhmikosR** [comment]
You need to delete package-lock.json before installing the new packages.

**Comment by XhmikosR** [comment]
You need to run the bench script again after this; previously the old packages were used.

**Comment by jakubpawlowicz** [comment]
Yup, it looks good. Thanks guys for figuring it out!

**Comment by XhmikosR** [comment]
@diegourban: If you have time, see https://david-dm.org/GoalSmashers/css-minification-benchmark?type=dev

On a side note, we might no longer need es6-promise now that node.js 4 is required.

**Pull request merged**
