### PR TITLE
csso 2.0.x

### PR DESCRIPTION
**Pull request by denji**
https://github.com/css/csso/releases/tag/v2.0.0

### CODE REVIEW

**Comment by XhmikosR** [comment]
I think this requires changes from our side due to the API changes.

**Comment by denji** [comment]
@XhmikosR This fragment of code?

```js
  'csso': csso.minify,
  'csso (restructuring off)': function(source) {
    return csso.minify(source, { restructuring: false });
  },
```

**Comment by XhmikosR** [comment]
Yeah. From the release notes I see

```
var csso = require('csso');

// before
console.log(csso.minify(css));
console.log(csso.minify(css, { sourceMap: true }).css);

// now it's consistent
console.log(csso.minify(css).css);
console.log(csso.minify(css, { sourceMap: true }).css);
```

**Comment by denji** [comment]
@XhmikosR Ready 🚢

**Comment by XhmikosR** [comment]
@denji; please check the failures.

**Pull request merged**
